ascii.wad
sprites/dynamic_mapvote/blue-shift.spr
sprites/dynamic_mapvote/half-life.spr
sprites/dynamic_mapvote/opposing-force.spr
sprites/dynamic_mapvote/uplink.spr
sprites/dynamic_mapvote/TH-ep1.spr
sprites/dynamic_mapvote/TH-ep2.spr
sprites/dynamic_mapvote/TH-ep3.spr
sprites/dynamic_mapvote/blackmesaepf.spr
