ascii.wad
sprites/dynamic_mapvote/half-lifea.spr
sprites/dynamic_mapvote/opposing-force.spr
sprites/dynamic_mapvote/blue-shift.spr
sprites/dynamic_mapvote/decay.spr
sprites/dynamic_mapvote/uplinka.spr
sprites/dynamic_mapvote/blackmesaepf.spr
sprites/dynamic_mapvote/instinct_v3.spr
sprites/dynamic_mapvote/TH-ep1.spr
sprites/dynamic_mapvote/TH-ep2.spr
sprites/dynamic_mapvote/TH-ep3.spr
