sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/cubemath/key.mdl
models/cubemath/padlock.mdl
models/cubemath/arrow2d.mdl
models/player/nsmbw_wendy/nsmbw_wendy.bmp
models/player/nsmbw_wendy/nsmbw_wendy.mdl
models/player/crash_bandicoot/crash_bandicoot.bmp
models/player/crash_bandicoot/crash_bandicoot.mdl
