sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
gfx/env/hackbk.bmp
gfx/env/hackbk.tga
gfx/env/hackdn.bmp
gfx/env/hackdn.tga
gfx/env/hackft.bmp
gfx/env/hackft.tga
gfx/env/hacklf.bmp
gfx/env/hacklf.tga
gfx/env/hackrt.bmp
gfx/env/hackrt.tga
gfx/env/hackup.bmp
gfx/env/hackup.tga
